server:
  port: 9769
spring:
  application:
    name: config-server
  #config server从本地读取配置文件
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared #读取配置的路径
#  profiles:
#    active: native  #config server从本地读取配置

  #config server从 github 仓库读取配置文件
  cloud:
    config:
      server:
        git:
          uri: https://github.com/superHeroJLS/SpringCloudConfig.git
          search-paths: configs
          username: 1257892551@qq.com
          password: james19950608
          default-label: main #默认branch

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResult=utf8
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    appname: config-server
    lease-renewal-interval-in-seconds: 30 #租约续期间隔（心跳间隔）
