server:
  port: 8080

#自定义配置
my:
  name: 'spring boot'
  age: 10
  number: ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'am ${my.name}


#actuator配置
management:
  security:
    enabled: false

#datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?useUnicode=true&characterEncoding=utf8&characterSetResult=utf8
    username: root
    password: 123456
  #spring data jpa 配置
  jpa:
    hibernate:
      ddl-auto: update #第一次建表create，后面用update
    show-sql: true
  #redis 配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500




