server:
  port: 8769
spring:
  application:
    name: hystrix-dashboard-trubine
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResult=utf8
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #这个hystrix-dashboard-turbien服务也需要注册到eureka-server上
turbine:
  aggregator:
    clusterConfig: default
  app-config: eureka-client-consumer,eureka-feign-client #hystrix-dashboard对应的服务名称（eureka.instance.appname)
  cluster-name-expression: new String("default")