spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  application:
    name: spring-boot-security
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-security?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResult=utf8
    username: root
    password: 123456

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true