server:
  port: 9411
spring:
  application:
    name: zipkin-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-zipkin?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResult=utf8
    username: root
    password: 123456
  # 使用消息组件Rabbitmq接受Zipkin的链路数据
  rabbitmq:
    host: 192.168.4.169
    port: 5672
    username: guest
    password: guest
zipkin:
  storage:
    type: mysql #Zipkin Server内存中的链路数据存储到Mysql数据库中

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
