server:
  port: 5001
spring:
  application:
    name: gateway-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResult=utf8
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:9411 #Zipkin Server的地址
  sleuth:
    sampler:
      percentage: 1.0 #Zipkin以100%的概率将链路数据上传给Zipkin Server，默认为0.1，通过HTTP方式上传
  # 使用消息组件Rabbitmq将Zipkin的链路数据上传至Zipkin Server，不使用HTTP方式上传
  rabbitmq:
    host: 192.168.4.169
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    userapi:
      path: /userapi/**
      serviceId: user-service